### ISSUE TITLE
[Problem] It stops while indexing.

### ISSUE THREAD

**Issue by jgimeno** [php-vim/phpcd.vim#35]
Hi, I just found in a project of mine that it starts indexing, but in the middle of the index process it stops the progress line. I don't get any feedback of why there was a problem with the indexing.

Is there any way to log how the indexing process is going and if it fails what was the problem?

**Comment by przepompownia** [comment]
Hi Jonathan

Currently `PHPID` daemon writes logs into `.phpcd.log` file in the home directory. The logger is still enabled by default (I would like to give the choice whether to write logs log or not, but not yet).

Example log usage in problematic line, e.g. in index() of PHPID:
```
$this->logger->debug('while body start: ', $this->class_map);
```
Debugging of forked process using `Xdebug` may be problematic (see https://bugs.xdebug.org/view.php?id=938 )

You can simply run `PHPID` without running vim to debug indexing because index() is called from the script at the beginning without interaction with vim. First, from the project directory remove `.phpcd` directory generated by `index()`. Next, from `phpcd.vim` run
```
XDEBUG_CONFIG="idekey=asdasd" php ./php/main.php /path/to/project/dir PHPID
```
I hope that it will be helpful to get more informations needed to find the bug.
